// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtgo-qb3Yq_fNtQEaWBrPuS4RJ_QaT-ls',
    appId: '1:1033323424381:web:f70d8caede9bdecf6b5f14',
    messagingSenderId: '1033323424381',
    projectId: 'chatapp-7e18d',
    authDomain: 'chatapp-7e18d.firebaseapp.com',
    storageBucket: 'chatapp-7e18d.appspot.com',
    measurementId: 'G-08EFNFKYF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvEumKhdxxEKgAtivhA_29_8eoAdR99cU',
    appId: '1:1033323424381:android:6d1f0b1bcbef0a2a6b5f14',
    messagingSenderId: '1033323424381',
    projectId: 'chatapp-7e18d',
    storageBucket: 'chatapp-7e18d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoIb5fIriWDM_Hz1zYmRz1vY0uJF8NrS0',
    appId: '1:1033323424381:ios:c5afa94f172163276b5f14',
    messagingSenderId: '1033323424381',
    projectId: 'chatapp-7e18d',
    storageBucket: 'chatapp-7e18d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoIb5fIriWDM_Hz1zYmRz1vY0uJF8NrS0',
    appId: '1:1033323424381:ios:3bfdb504e59c05676b5f14',
    messagingSenderId: '1033323424381',
    projectId: 'chatapp-7e18d',
    storageBucket: 'chatapp-7e18d.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
